### ISSUE TITLE
Building a .proto with an underscore/dot in its name is removed from the generated module.

### ISSUE THREAD

**Issue by csharad** [tower-rs/tower-grpc#129]
I have a proto file at `proto/hello_world.proto` and after the build using `tower_grpc_build` a module `helloworld.rs` is generated skipping any underscores.

I also tried it with `hello.world.proto` and it is also removed.

I am trying to follow rust naming schemes for module names and the proto files. Is this an intended behavior?

**Comment by seanmonstar** [comment]
I believe the name is taken from the `package` line in the `.proto` file. For example, in the `route_guide.proto`, since it has `package routeguide`, the generated file is `routeguide.rs`: https://github.com/tower-rs/tower-grpc/blob/fe2c454cb7e486b75310c13b59306e4e1d3625f3/tower-grpc-examples/proto/routeguide/route_guide.proto#L21

**Comment by csharad** [comment]
Yeah, that was it. Thanks!
