### ISSUE TITLE
Refine Error type

### ISSUE THREAD

**Issue by carllerche** [tower-rs/tower-grpc#6]
Does the error type need to be generic over `Inner`? Only clients need to be able to customize the inner type. Should there be separate error types for client and server?

**Comment by vorner** [comment]
Also, slightly related, they probably should be `Error`s or something similar 😇. (similar to https://github.com/tower-rs/tower-h2/issues/15).

I did some experiments and they fight a bit against proper error handling.

**Comment by aep** [comment]
woudnt it be useful if the server could return an io::Error which gets mapped to an error code?

**Comment by carllerche** [comment]
@vorner yes... it probably should impl `std::Errror` too...

@aep Well, you can always map any error to a gRPC error? I'm not entirely sure that I follow the question.

**Comment by plumenator** [comment]
Also, the generated code for `prost` forces `Inner` to `()` anyway. Furthermore, `client::grpc::Error` in the generated code is private, so it's un-referrable from application code.

**Comment by per-gron** [comment]
Is there a reason why the Error type can be anything else than the `Grpc` variant of the `Error` enum? The gRPC error codes are designed to represent all errors that can happen when making gRPC calls, including ones that are not from the other host. The [documentation in the grpc repo](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) lists how various errors should be mapped to gRPC status codes.

In my usage of tower-grpc the fact that there is no one error type has been a pretty big source of annoyance, maybe because I know that error handling in the other languages is so much simpler. It's a pain to have to explicitly convert between different instantiations of the `tower_grpc::Error` type. I also don't really see the value of exposing errors that are as detailed as `ProtocolError` to the end user of the library. I can't think of a situation where I would want to handle `MissingTrailers` and `UnexpectedEof` errors differently; they are all just protocol errors that my application can't really recover from.

The C++ gRPC library has an [error type](https://github.com/grpc/grpc/blob/master/include/grpcpp/impl/codegen/status.h) that has the error code plus an error message and an untyped (protobuf) binary string with more information about the error. To me that seems like it would be more usable than what tower-grpc has today.

**Comment by per-gron** [comment]
@carllerche I wrote some thoughts in #104. I think providing more debugging insight is valuable, but the gRPC `Status` type already allows that in its freeform error message string and binary error information fields. It's not very machine readable friendly but that's not necessary for debugging.

**Comment by carllerche** [comment]
@per-gron Should this issue be closed then?

**Comment by per-gron** [comment]
@carllerche hopefully soon. I'm not quite done yet, the `Inner` enum variant is still there. I think some of the  Error handling of the interop test client code can be made simpler if that's simplified too.

Actually maybe this is a good time to convert that code to use async/await. Perhaps the error handling won't be as painful then. I don't have the experience to intuitively know how the error handling code will with async/await.

**Comment by seanmonstar** [comment]
Finished in https://github.com/tower-rs/tower-grpc/pull/116
