### ISSUE TITLE
Creating a Client Call Outside of Tokio Core

### ISSUE THREAD

**Issue by nevi-me** [tower-rs/tower-grpc#84]
I've been using tower-grpc server, and now I have a need to use it for a client.

I've followed the routeguide example, and got it working, but I want to use my client with another library (actix).

In the routeguide example (https://github.com/tower-rs/tower-grpc/blob/master/tower-grpc-examples/src/routeguide/client.rs#L64), a call is made with

```rust
    let mut core = Core::new().unwrap();
    let response = core.run({
        client.get_feature(Request::new(Point {
            latitude: 409146138,
            longitude: -746188906,
        }))
    }).unwrap();
```

However, when I try doing the same inside of an actor, I get an error about recursively calling `Core`.

I tried doing a `client.get_feature()` without wrapping it in a `core.run()`, but then my thread seems to get blocked indefinitely.

How can I call a client without using a core?

**Comment by hawkw** [comment]
Hi @nevi-me, I'm not particularly familiar with `actix`, but I think that you should be able to replace the call to `core.run` with any function that executes a future. It depends on what exactly you're trying to accomplish, but I think in `actix` you can spawn futures using [`Arbiter::spawn`](https://docs.rs/actix/0.7.4/actix/struct.Arbiter.html#method.spawn). Rather than being able to access the result of evaluating the response, though, you will have to compose additional futures to do whatever it is you want to do once you have the response, as `Arbiter::spawn` requires the spawned future to have the type `Future<Item=(), Error=()>`.

**Comment by nevi-me** [comment]
Thanks @hawkw , if I save my future in a variable, I get `fut: ResponseFuture<Feature, ResonseFuture, <unknown>>`. How would I convert a `ResponseFuture` into a normal `Future<Item=(), Error=()>`?

```rust
let fut = client.get_feature(Request::new(Point {
            latitude: 409146138,
            longitude: -746188906,
        }))
```

**Comment by nevi-me** [comment]
Your solution worked, thanks!
